backend:
  name: github
  repo: ymr-39/rainy

media_folder: src/assets
public_folder: assets

slug:
  encoding: "unicode"

collections:
  - name: blog
    label: Blog
    folder: src/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }